### ISSUE TITLE
Intake datasets

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#184]
A general call to provide ideas for datasets and catalogs: https://github.com/ContinuumIO/intake-datasets

cc @pzwang @seibert @mmccarty

**Comment by atg-abhishek** [comment]
I'd suggest that a lot of the datasets here could serve as great examples for that - http://archive.ics.uci.edu/ml/index.php (unless I'm misunderstanding the purpose of this issue) @martindurant

**Comment by martindurant** [comment]
huge list of links here: https://www.datasciencecentral.com/profiles/blogs/great-github-list-of-public-data-sets , a real grab-bag of styles and interfaces

**Comment by atg-abhishek** [comment]
I think it might also be an interesting idea to add support for some of the benchmark style datasets, eg CIFAR 10, MNIST, IMDB, YouTube-8M, etc as starting examples, especially in a machine learning context

**Comment by martindurant** [comment]
To @atg-abhishek , and others that might contribute ideas here or at  https://github.com/ContinuumIO/intake-datasets 

Ideally, datasets would include as much information as possible, such that the job of creating data-set specs or catalog interfaces to the data services is as easy as possible. Actual catalogs (YAML files) or catalog driver classes would be great! 

The lists of links above are fascinating and useful, and give a glimpse of the amount of data out there to be harvested. Unfortunately, a little clicking around will show that, generally speaking, most links on the target pages are in fact further screens if information and instruction, and it is not usually apparent how to get at the raw data, or how to interpret what is there in a programmatic way. For example, many require registration and careful reading to figure out how to call an API, the file formats supplied, or even just the meanings of columns for simple CSV data.

**Comment by martindurant** [comment]
xref https://github.com/ContinuumIO/intake-datasets/issues/1

**Comment by jacobtomlinson** [comment]
Just wanted to add https://aws.amazon.com/earth/

**Comment by martindurant** [comment]
Thanks, @jacobtomlinson .
Landsat has, of course, come up a lot (@jsignell , want to comment?).

However the page you link gives patchy information in the manner that I've found often, which makes the creation of Intake catalogues hard. I tried two links so far:
- National Agriculture Imagery Program is "deprecated" (may be OK), but the [docs](https://docs.opendata.aws/aws-naip/readme.html) say it is a bunch of geoTIFFS on s3, so that's OK
- Terrain Tiles has a normal looking description page, but the documentation is a 404.

What I'd really like is for someone (not me!) to convert the descriptive pages into catalogues! Unfortunately, that someone would need to know something about how Intake works.

**Comment by jacobtomlinson** [comment]
I agree with all of that. 

A bigger problem is that these datasets are often large, made up of hundreds of thousands of files and are constantly being added to. I'm keen to hear how we could use intake to catalog these.

**Comment by martindurant** [comment]
I suppose that's true; and while normal s3 `ls()` is fine for getting a set of files, I really don't know what other data users may be doing as the number of files grows very large. Perhaps, for each big data-set, additional specifics required about how the file names are structured and what data has been filled so far, so that a query can efficiently get the right pieces without even listing all the available files. There is the obvious option, here, that Intake (of fsspec?) could locally cache file-lists for quick lookup.

Typically, the examples included with public data-sets like these touch some specific set of data from when the archive was new...

**Comment by jsignell** [comment]
I have done some catalog-making with the landsat archives on gcs and s3. I generally use templating to allow the user to set the row and path but I don't have a good way of selecting collection date. There might be a use case for the GUI where we query to get a list of all the available dates, and then have a selector. Here's an example of what I've done: 

```yaml
  amazon_landsat_band:
    description: Landsat bands from Amazon Web Services S3
    driver: rasterio
    parameters:
      path:
        description: landsat path
        type: int
      row:
        description: landsat row
        type: int
      product_id:
        description: landsat file id
        type: str
      band:
        description: band
        type: int
    cache:
      - argkey: urlpath
        regex: 'landsat-pds'
        type: file
    args:
      urlpath: s3://landsat-pds/c1/L8/{{ '%03d' % path }}/{{ '%03d' % row }}/{{ product_id }}/{{ product_id }}_B{{ band }}.TIF
      chunks:
        band: 1
        x: 256
        y: 256
      storage_options: {'anon': True}
```

https://github.com/pyviz-topics/EarthML/blob/8b51905d6e230b2330d46fe54bed6579ba11bcd0/examples/catalog.yml#L108-L134
