### ISSUE TITLE
Cache files get created in the current directory

### ISSUE THREAD

**Issue by psarka** [ContinuumIO/intake#254]
Perhaps thanks to https://github.com/ContinuumIO/intake/issues/151, cache files are now always created in the current directory, even though the `cache_dir` is `~/.intake/` and documentation mentions that `~/.intake/` is the default location (and it ends up containing `cache_metadata.json`, just not the files themselves)

Looking here https://github.com/ContinuumIO/intake/blob/da2809d13045dc97dd3753f5ac4bcc9e19299d74/intake/source/cache.py#L322 it seems to me that the cache directory is not taken into account when creating `files_out`.

repro.py:
```
import intake
intake.open_catalog('123.yml').onetwothree.read()
```

123.yml:
```
metadata:
  version: 1

sources:
  onetwothree:
    description: bucket csv test
    driver: csv
    args:
      urlpath: 'gs://puodas/123.csv'
      storage_options:
        token: "anon"
    cache:
      - argkey: urlpath
        regex: 'gs://puodas/'
        type: file
```
