### ISSUE TITLE
Cache paths are not file system safe

### ISSUE THREAD

**Issue by psarka** [ContinuumIO/intake#265]
The function `sanitize_path` (line 26 in `intake/source/cache.py`) does not sufficiently sanitize the path. As far as I can tell, it does not protect against forbidden words, characters, endings, and does not protect from too long directory and file names.

To reproduce one example, run this on a windows machine:

repro.py
```
import intake
intake.open_catalog('123.yml').onetwothree.read()
```

123.yml:
```
metadata:
  version: 1

sources:
  onetwothree:
    description: bucket csv test
    driver: csv
    args:
      urlpath: 'gs://puodas/con.csv'
      storage_options:
        token: "anon"
    cache:
      - argkey: urlpath
        regex: 'puodas'
        type: file
```
