### ISSUE TITLE
Intake breaks merge key functionality in yaml

### ISSUE THREAD

**Issue by psarka** [ContinuumIO/intake#269]
Hi all, the last one from me (moving to other things) :)

Yaml has a feature of anchors and merge keys, which I think could be of interest to the intake users, as it allows to reduce the duplication of definitions in the catalogue files. Roughly like this:

```yaml
metadata:
  version: 1

cache_settings: &cache_settings
  cache:
    - argkey: urlpath
      type: file

parameters: &token_settings
  token_file:
    description: token file
    type: str
    default: env(TOKEN)

storage_options: &storage_settings
  storage_options:
    token: '{{ token_file }}'

sources:
  a_file:
    <<: *cache_settings
    description: a file
    driver: csv
    args:
      <<: *storage_settings
      urlpath: 'gs://some/url/a.csv'
    parameters:
      <<: *token_settings
```

However, currently intake breaks the merge key functionality. Here is a small example for repro:

merge.yaml:
```yaml
foo: &anchor
  K1: "One"
  K2: "Two"

bar:
  <<: *anchor
  K2: "Deuce"
  K3: "Three"
```
this_breaks.py
```python
import intake
import yaml

yaml.load(open('merge.yaml'))
```

If you remove the intake import, it works. I have not investigated what's the cause, and the error I get is
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "merge.yaml", line 6, column 3
```

**Comment by seibert** [comment]
Looking back into the YAML parsing code, I am now highly suspicious of this block, which alters the global configuration of the `yaml` module:

https://github.com/ContinuumIO/intake/blob/master/intake/catalog/local.py#L277-L298

**Comment by martindurant** [comment]
I only recently came across this syntax, and it turns out that Intake generated and used it automaticlaly by itself in the context of #237 :
```
  e66c74ee130fc21cd5101404c6537e50:
    args:
      component: null
      storage_options: null
      url: /Users/mdurant/.intake/persisted/e66c74ee130fc21cd5101404c6537e50
    description: ''
    driver: intake.source.zarr.ZarrArraySource
    metadata:
      cat:
        args: !!python/tuple
        - /Users/mdurant/code/intake/intake/source/tests/sources.yaml
        cls: intake.catalog.local.YAMLFileCatalog
        kwargs: {}
      original_metadata: &id002
        cache: []
        catalog_dir: /Users/mdurant/code/intake/intake/source/tests/
      original_name: zarr1
      original_source:
        args: !!python/tuple []
        cls: intake.source.zarr.ZarrArraySource
        kwargs:
          metadata: *id002
          url: /Users/mdurant/code/intake/intake/source/tests//data.zarr
      original_tok: e66c74ee130fc21cd5101404c6537e50
      persist_kwargs: {}
      timestamp: 1550503722.15875
      ttl: null
```

Notice that this is a little different than your example, particularly it doesn't have the "<<" labels - maybe that's the problem?
