### ISSUE TITLE
Proposal for allowing catalog sources to reference each other

### ISSUE THREAD

**Issue by gbrener** [ContinuumIO/intake#32]
While writing SQL data source expressions, I realized that doing intra-database joins will require calling into pandas/dask outside of _intake_ after the catalog source `read()` call. For example, given two tables and desired result:

`name_mappings` table:

id | name
--|----------
1 | "George"
2 |  "Paul"

`ages` table:

name | age
--|---------
2 | 75
1 | 22

Desired result:

name | age
--|---------
"Paul" | 75
"George" | 22

We can use the "ages_join" source in the following _catalog.yml_ directly, as long as both tables are in the same database:

```
plugins:
  source:
    - module: intake_postgres

sources:
  - name: name_mappings
    driver: postgres
    args:
      uri: '...'
      sql_expr: 'select id, name from name_mappings'

  - name: ages
    driver: postgres
    args:
      uri: '...'
      sql_expr: 'select name, age from ages'

  - name: ages_join
    driver: postgres
    args:
      uri: '...'
      sql_expr: |
        select name_mappings.name, ages.age
        from age
        inner join name_mappings on ages.name = name_mappings.id
```

However, if the tables are in separate databases - that is, if the _uri_ fields are different between _ages_ and _name\_mappings_ - we would need to call `.read()` on both data sources and then do a pandas/dask `.merge()` afterward. This is usually not an issue, but can be a bit cumbersome in the case where more than one column needs to be normalized.

One approach that might save users some boilerplate would be something like the following:

```
  - name: ages_join_external_db
    driver: postgres
    args:
      uri: '...'
      sql_expr: !template "select {{ map_source('name_mappings', name=id) }}.name, ages.age from age"
```

Where we could allow any of the SELECT targets to reference a predefined data source in the catalog. When the _intake-postgres_ plugin sees something like this, it could rely on the metadata gleaned from `discover()` to internally do a ".merge()" (aka a SQL-style JOIN) on the result of the query, with the knowledge that `catalog.ages.name` maps to `catalog.name_mappings.id`.
