### ISSUE TITLE
Metadata fields used for plotting

### ISSUE THREAD

**Issue by philippjfr** [ContinuumIO/intake#53]
Catalogues allow defining arbitrary metadata to be associated with a dataset, which could be very useful to provide hints to the plotting system. Specifically there are two types of options that could be useful in this regard:

* Plot options: Options passed directly to the plotting API, e.g. datashade, width, height, colorbar, logx, logy etc. 
* Field annotations: Additional metadata to associate with dataset fields (i.e. columns in a dataframe), including labels (used for axis labels), units (also for axis labels), ranges (to set axis and color range limits)

It would be good to decide on the syntax to express these options. I'm currently imagining something like this: 

```
sources:
  nyc_taxi:
    description: NYC Taxi dataset
    driver: parquet
    args:
      urlpath: 's3://datashader-data/nyc_taxi_wide.parq'
	metadata:
	  plot:
	    datashade: true
          fields:
            dropoff_x:
              label: 'Longitude'
            dropoff_y:
              label: 'Latitude'
            fare_amount:
              label: 'Fare'
              unit: '$'
              range: [0, 100]
```

Other suggestions with (perhaps with less nesting) would be welcome though.

**Comment by martindurant** [comment]
With the new plotting system, I assume this is ready to implement - it'll need some code somewhere to turn the metadata into arguments passed to holoplots.

**Comment by philippjfr** [comment]
That's right. Should be quite straightforward, the ``plot`` metadata field can be passed 1-to-1 to the plotting class, and I'll create an API to declare the field metadata. Only thing to consider is validation, is runtime validation (i.e. when actually plotting the data) sufficient or should there be some way to validate the metadata at an earlier stage?

**Comment by martindurant** [comment]
I think its fine not to validate the plotting arguments at cat load time, and raise only when the plot is attempted - this is true for other source arguments. After all, the metadata in the source can be overridden by the user.

**Comment by philippjfr** [comment]
This has now been implemented as part of #83 and works well. Having played with it a bit I've been considering a fairly simple extension to this I'd like to get some thoughts on. Much in the way that the catalog.yml can define a number of datasources, I'm wondering whether each datasource can also define a catalogue of pre-defined plots. Currently the ``plot`` metadata key defines the default arguments for one plot. This has obvious limitations, once you've defined various ``plot`` options they will interfere with regular usage of the plot method since they will combine in weird ways with options the user supplies at run time. Take this example:

```yaml
sources:
  nyc_taxi:
    description: NYC Taxi dataset
    driver: parquet
    args:
      urlpath: 's3://datashader-data/nyc_taxi_wide.parq'
    metadata:
      plot:
        kind: 'scatter'
        x: dropoff_x
        y: dropoff_y
        datashade: true
```

In the current scheme, unless otherwise specified, the plot method will always default to plotting a ``scatter`` with x and y set to the dropoff_x/y columns. As an alternative I'd suggest something like this:

```yaml
sources:
  nyc_taxi:
    description: NYC Taxi dataset
    driver: parquet
    args:
      urlpath: 's3://datashader-data/nyc_taxi_wide.parq'
    metadata:
      plot:
        datashade: true
      plots:
        - name: dropoff_scatter
          kind: 'scatter'
          x: dropoff_x
          y: dropoff_y
        - name: fare_scatter
          kind: 'scatter'
          x: fare_amount
          y: tip_amount
```

You can still define global options via the ``plot`` key but can define specific plots via the ``plots``. When loading this catalogue it could now make these predefined plot types available like so:

```python
cat.nyc_taxi.plot.fare_scatter()
```

and let you override or supply additional options like so:

```python
cat.nyc_taxi.plot.dropoff_scatter(cmap='viridis')
```

@jbednar Would be good to get your thoughts here as well.

**Comment by jbednar** [comment]
Looks good to me.  A couple of questions:

1. What would cat.nyc_taxi.plot() do, when plots is present?  Plot the first one in the list?
2. What happens when user-defined plots have the same name as a HoloViews or GeoViews element?  Both of those seem to be using the same attribute space of the plot method, right?  
3. How can people select a GeoViews rather than HoloViews `kind`?  Having a crs that's non-None?

For 2, it seems like there will often be conflicts, given that the names of HoloViews and GeoViews elements are the names of types of plots, and users are likely to want to declare different types of plots in this way. (Here are the violin options, the curve options, etc.)  Or is that a feature, in that people can use this mechanism to define options per plot type?

**Comment by philippjfr** [comment]
>What would cat.nyc_taxi.plot() do, when plots is present? Plot the first one in the list?

No, that's precisely what this aims to avoid, it provides a way to persist plot definitions without overriding the default behavior. The example I laid out would be equivalent to ``cat.nyc_taxi.plot(datashade=True)`` as metadata on the ``plot`` key will continue to be applied globally.

>What happens when user-defined plots have the same name as a HoloViews or GeoViews element? Both of those seem to be using the same attribute space of the plot method, right?

True, they could clash, not sure that's a major problem if we document it. As you say users could override the behavior of a plot type in this way. If they decide to declare something like:

```yaml
plots:
  - name: scatter
    kind: 'line'
```

I think that's their problem.

>How can people select a GeoViews rather than HoloViews kind? Having a crs that's non-None?

That's unrelated to this proposal but that is correct, if the supplied ``kind``, e.g. image and quadmesh, has a GeoViews implementation then it will switch to a GeoViews element if the crs is supplied. I have not yet implemented a way to persist the ``crs`` in a yaml file.
